[package]
name = "esp-idf-hal"
version = "0.13.0"
authors = ["sapir <yasapir@gmail.com>", "Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp8266", "idf"]
description = "A Hardware abstraction layer for Espressif's ESP family of microcontrollers based on the ESP-IDF framework."
repository = "https://github.com/ivmarkov/esp-idf-hal"
license = "MIT"

# no xtensa in regular compiler yet
[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"

[features]
default = ["std"]

std = ["esp-idf-sys/std"]

[dependencies]
nb = "0.1.2"
mutex-trait = "0.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
esp-idf-sys = {version = "0.13", git = "https://github.com/ivmarkov/esp-idf-sys.git", default-features = false}
#esp-idf-sys = { version = "*", path = "../esp-idf-sys", default-features = false}

[dev-dependencies]
panic-halt = "0.2.0"
